#!/usr/bin/env python3
"""
Quick setup script for .env file
Run this to easily configure your Firebase environment variables
"""

import os
import sys

def create_env_file():
    print("🔥 Firebase Environment Setup")
    print("=" * 50)
    
    if os.path.exists(".env"):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("❌ Setup cancelled.")
            return
    
    print("\n📋 Please provide your Firebase configuration:")
    print("You can find these in Firebase Console → Project Settings → General → Your apps → Config")
    print()
    
    firebase_config = {}
    
    # Collect Firebase configuration
    config_fields = [
        ("FIREBASE_API_KEY", "API Key", "AIzaSyC..."),
        ("FIREBASE_AUTH_DOMAIN", "Auth Domain", "your-project.firebaseapp.com"),
        ("FIREBASE_PROJECT_ID", "Project ID", "your-project-id"),
        ("FIREBASE_STORAGE_BUCKET", "Storage Bucket", "your-project.appspot.com"),
        ("FIREBASE_MESSAGING_SENDER_ID", "Messaging Sender ID", "123456789"),
        ("FIREBASE_APP_ID", "App ID", "1:123456789:web:abcdef123456"),
        ("FIREBASE_MEASUREMENT_ID", "Measurement ID (optional)", "G-XXXXXXXXXX"),
        ("FIREBASE_DATABASE_URL", "Database URL", "https://your-project-default-rtdb.firebaseio.com")
    ]
    
    for env_key, display_name, example in config_fields:
        while True:
            value = input(f"{display_name} (e.g., {example}): ").strip()
            if value or "optional" in display_name.lower():
                firebase_config[env_key] = value
                break
            print("❌ This field is required. Please enter a value.")
    
    # Create .env file
    env_content = "# Firebase Configuration\n"
    env_content += "# Generated by setup-env.py\n\n"
    
    for key, value in firebase_config.items():
        env_content += f"{key}={value}\n"
    
    env_content += "\n# Application Settings\n"
    env_content += "DEBUG=True\n"
    env_content += "LOG_LEVEL=INFO\n"
    env_content += "ENVIRONMENT=development\n"
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    print("🔒 Make sure .env is in your .gitignore (already done)")
    print("🚀 You can now run your app with: uvicorn app:app --reload")
    print("\n📝 For production deployment:")
    print("   - Don't upload .env file to Render")
    print("   - Set these same variables in Render environment settings")

if __name__ == "__main__":
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n❌ Setup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)